apiVersion: v1
kind: Service
metadata:
  name: random-number-client-svc
spec:
  selector:
    app: random-number-client
  ports:
  - port: 8080         
    targetPort: 5000 
    nodePort: 30080
  type: LoadBalancer
